package utils;

import java.io.Serializable;

/**
 * different types of messages
 */
public enum MessageTypes implements Serializable {
    JOIN_REQUEST,
    ALL_PLAYERS_JOINED,
    PLAYER_IS_READY,
    ACTIONS_EXIT,
    END_OF_GAME,

    INFO,
    SILENCE_PLAYER,
    COMMAND_REFUSED,
    COMMAND_ACCEPTED,
    NORMAL_CHAT,
    ANSWER_TO_WATCH,
    ANSWER_TO_CANCEL,
    QUESTION_TO_CANCEL,
    QUESTION_TO_WATCH,
    CLOSE_CHATROOM,
    TEAMMATES,
    VOTE_RESULT,

    ACTIONS_GOD_SET_ROLE,
    ACTIONS_GOD_ORDERED_START,
    ACTIONS_GOD_ORDERED_VOTE,
    ACTIONS_GOD_ORDERED_NIGHT_ACT,
    ACTIONS_GOD_ORDERED_DAY_PUBLIC_CHAT,
    ACTIONS_GOD_ORDERED_FIRST_NIGHT_GREETING,


    ACTIONS_PLAYER_VOTED, // JUST THE VOTING IN THE DAY
    ACTIONS_GODFATHER_ORDERED_KILL,
    ACTIONS_LECTER_ORDERED_SAVE,
    ACTIONS_DOCTOR_ORDERED_SAVE,
    ACTIONS_DETECTIVE_ORDERED_INQUIRY,
    ACTIONS_SNIPER_ORDERED_KILL,
    ACTIONS_PSYCHOLOGIST_ORDERED_SILENCE,
    ACTIONS_DIEHARD_ORDERED_INQUIRY,

}
