package utils;

import java.io.Serializable;

public enum MessageTypes implements Serializable {
    JOIN_REQUEST,
    ALL_PLAYERS_JOINED,
    PLAYER_IS_READY,
    ACTIONS_EXIT,
    FAKE_MESSAGE,
    END_OF_GAME,

    INFO,
    COMMAND_REFUSED,
    NORMAL_CHAT,

    ACTIONS_GOD_SET_ROLE,
    ACTIONS_GOD_ORDERED_START,
    ACTIONS_GOD_ORDERED_WAIT,
    ACTIONS_GOD_ORDERED_VOTE,
    ACTIONS_GOD_ORDERED_NIGHT_ACT,
    ACTIONS_GOD_ORDERED_DAY_PUBLIC_CHAT,
    ACTIONS_GOD_ORDERED_FIRST_NIGHT_GREETING,

    ACTIONS_PLAYER_VOTED, // JUST THE VOTING IN THE DAY
    ACTIONS_GODFATHER_ORDERED_KILL,
    ACTIONS_LECTER_ORDERED_SAVE,
    ACTIONS_DOCTOR_ORDERED_SAVE,
    ACTIONS_DETECTIVE_ORDERED_INQUIRY,
    ACTIONS_SNIPER_ORDERED_KILL,
    ACTIONS_MAYOR_ORDERED_CANCEL_VOTING,
    ACTIONS_PSYCHOLOGIST_ORDERED_SILENCE,
    ACTIONS_DIEHARD_ORDERED_INQUIRY,

}
